# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Interest.create(name: 'Animals', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Bird Watching', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Birds', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Cats', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Dogs', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Exotic Pets', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Fish', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Pets', subcategory: 'Animals', category: 'Animals and Outdoors')
Interest.create(name: 'Agriculture', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Camping', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Climbing', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Environment', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Forestry', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Hiking', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Nature', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Outdoors', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Scouting', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Survivalist', subcategory: 'Outdoors', category: 'Animals and Outdoors')
Interest.create(name: 'Advertising', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Architecture', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'C.A.D.', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Computer Graphics', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Design', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Desktop Publishing', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Graphic Design', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Industrial Design', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Photoshop', subcategory: 'Design', category: 'Arts')
Interest.create(name: 'Art History', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Arts', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Drawing', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Fine Arts', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Painting', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Photography', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Postmodernism', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Sculpting', subcategory: 'Fine Arts', category: 'Arts')
Interest.create(name: 'Ballet', subcategory: 'Performing Arts', category: 'Arts')
Interest.create(name: 'Dancing', subcategory: 'Performing Arts', category: 'Arts')
Interest.create(name: 'Live Theatre', subcategory: 'Performing Arts', category: 'Arts')
Interest.create(name: 'Musicals', subcategory: 'Performing Arts', category: 'Arts')
Interest.create(name: 'Performing Arts', subcategory: 'Performing Arts', category: 'Arts')
Interest.create(name: 'Business', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Career planning', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Consumer Info', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Entrepreneurship', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Home Business', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Management/HR', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Marketing', subcategory: 'Business and Careers', category: 'Education and Business')
Interest.create(name: 'Continuing Education', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'Education', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'Homeschooling', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'Library Resources', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'Research', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'Self Improvement', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'University/College', subcategory: 'Education', category: 'Education and Business')
Interest.create(name: 'Accounting', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Banking', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Capitalism', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Daytrading', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Economics', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Financial planning', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Insurance', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Investing', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Mutual Funds', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Options/Futures', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Real Estate', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Taxation', subcategory: 'Finance', category: 'Education and Business')
Interest.create(name: 'Antiques', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Christmas', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Collecting', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Crafts', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Crochet', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Dolls/Puppets', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Knitting', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Memorabilia', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Quilting', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Scrapbooking', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Sewing', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Woodworking', subcategory: 'Crafts', category: 'Fashions and Crafts')
Interest.create(name: 'Bargains/Coupons', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Beauty', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Clothing', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Ecommerce', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Fashion', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Jewelry', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Shopping', subcategory: 'Fashion and Beauty', category: 'Fashions and Crafts')
Interest.create(name: 'Genetics and Biology', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Anatomy', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Biomechanics', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Biotech', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Cognitive Science', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Evolution', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Genetics', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Microbiology', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Neuroscience', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Pharmacology', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Physiology', subcategory: 'Health', category: 'Health')
Interest.create(name: 'Alternative Health', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Antiaging', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Dentistry', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Doctors/Surgeons', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Ergonomics', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Health', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Kinesiology', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Medical Science', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Mental Health', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Nursing', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Physical Therapy', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Psychiatry', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Psychology', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Sexual Health', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Weight Loss', subcategory: 'Health Solutions', category: 'Health')
Interest.create(name: 'Alternative News', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Bisexual Culture', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Conspiracies', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Counterculture', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Crime', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Drugs', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Forensics', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Gay Culture', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Goth Culture', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Hedonism', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Lefthanded', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Lesbian Culture', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Paranormal', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Subculture', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'Tattoos/Piercing', subcategory: 'Alternative Culture', category: 'History and Culture')
Interest.create(name: 'American History', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Ancient History', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Anthropology', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Archaeology', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Classical Studies', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Cold War', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'History', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Medieval History', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Philosophy', subcategory: 'History', category: 'History and Culture')
Interest.create(name: 'Alcoholic Drinks', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Beer', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Beverages', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Cigars', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Coffee', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Food/Cooking', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Homebrewing', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Nutrition', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Restaurants', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Tea', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Vegetarian', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Wine', subcategory: 'Food and Beverages', category: 'Home and Travel')
Interest.create(name: 'Botany', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Construction', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Gardening', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Home Improvement', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Homemaking', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Interior Design', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Landscaping', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Restoration', subcategory: 'Home and Garden', category: 'Home and Travel')
Interest.create(name: 'Hotels', subcategory: 'Travel', category: 'Home and Travel')
Interest.create(name: 'Luxury', subcategory: 'Travel', category: 'Home and Travel')
Interest.create(name: 'Nightlife', subcategory: 'Travel', category: 'Home and Travel')
Interest.create(name: 'Spas', subcategory: 'Travel', category: 'Home and Travel')
Interest.create(name: 'Travel', subcategory: 'Travel', category: 'Home and Travel')
Interest.create(name: 'Humor', subcategory: 'Humor', category: 'Home and Travel')
Interest.create(name: 'Bizarre/Oddities', subcategory: 'Humor', category: 'Home and Travel')
Interest.create(name: 'Cyberculture', subcategory: 'Humor', category: 'Home and Travel')
Interest.create(name: 'Humor', subcategory: 'Humor', category: 'Home and Travel')
Interest.create(name: 'Satire', subcategory: 'Humor', category: 'Home and Travel')
Interest.create(name: 'American Lit.', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Biographies', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Books', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'British Literature', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Children\'s Books', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Fantasy Books', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Humanities', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Journalism', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Literature', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Mystery Novels', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Poetry', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Quotes', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Romance Novels', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Shakespeare', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Writing', subcategory: 'Literature', category: 'Literature')
Interest.create(name: 'Celtic Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Christian Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Classical Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Ethnic Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Gospel music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Latin Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Lounge Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Opera', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Vocal Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Dance Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Ambient Music', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'DJ\'s/Mixing', subcategory: 'Classical and World', category: 'Music')
Interest.create(name: 'Disco', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Drum\'n\'Bass', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Electronica/IDM', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'House music', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Industrial Music', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Rave Culture', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Techno', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Trance', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'TripHop/Downtempo', subcategory: 'Dance Music', category: 'Music')
Interest.create(name: 'Blues music', subcategory: 'Jazz and Blues', category: 'Music')
Interest.create(name: 'Funk', subcategory: 'Jazz and Blues', category: 'Music')
Interest.create(name: 'Jazz', subcategory: 'Jazz and Blues', category: 'Music')
Interest.create(name: 'Oldies Music', subcategory: 'Jazz and Blues', category: 'Music')
Interest.create(name: 'Reggae', subcategory: 'Jazz and Blues', category: 'Music')
Interest.create(name: 'Soul/R&B', subcategory: 'Jazz and Blues', category: 'Music')
Interest.create(name: 'Country music', subcategory: 'Popular Music', category: 'Music')
Interest.create(name: 'HipHop/Rap', subcategory: 'Popular Music', category: 'Music')
Interest.create(name: 'Karaoke', subcategory: 'Popular Music', category: 'Music')
Interest.create(name: 'Music', subcategory: 'Popular Music', category: 'Music')
Interest.create(name: 'Pop music', subcategory: 'Popular Music', category: 'Music')
Interest.create(name: 'Alternative Rock', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Britpop', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Classic Rock', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Folk music', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Heavy metal', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Indie Rock/Pop', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Punk Rock', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Rock music', subcategory: 'Rock Music', category: 'Music')
Interest.create(name: 'Guitar', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Music Composition', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Music Instruments', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Music Theory', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Musician Resources', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Percussion', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Radio Broadcasts', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Songwriting', subcategory: 'Songwriting', category: 'Music')
Interest.create(name: 'Activism', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Anarchism', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Communism', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Feminism', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Law', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Liberties/Rights', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Military', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'News(General)', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Socialism', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Sociology', subcategory: 'Activism and News', category: 'News and Politics')
Interest.create(name: 'Ethics', subcategory: 'Humanitarianism', category: 'News and Politics')
Interest.create(name: 'Humanitarianism', subcategory: 'Humanitarianism', category: 'News and Politics')
Interest.create(name: 'International Development', subcategory: 'Humanitarianism', category: 'News and Politics')
Interest.create(name: 'Nonprofit/Charity', subcategory: 'Humanitarianism', category: 'News and Politics')
Interest.create(name: 'Conservative Politics', subcategory: 'Politics', category: 'News and Politics')
Interest.create(name: 'Government', subcategory: 'Politics', category: 'News and Politics')
Interest.create(name: 'Liberal Politics', subcategory: 'Politics', category: 'News and Politics')
Interest.create(name: 'Political Science', subcategory: 'Politics', category: 'News and Politics')
Interest.create(name: 'Politics', subcategory: 'Politics', category: 'News and Politics')
Interest.create(name: 'Babies', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Divorce', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Entertaining Guests', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Family', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'For Kids', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Genealogy', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Kids', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Married Life', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Parenting', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Pregnancy/Birth', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Senior Citizens', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Teen Life', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Teen Parenting', subcategory: 'Family', category: 'Relationships and Family')
Interest.create(name: 'Dating Tips', subcategory: 'Relationships', category: 'Relationships and Family')
Interest.create(name: 'Matchmaking', subcategory: 'Relationships', category: 'Relationships and Family')
Interest.create(name: 'Men\'s Issues', subcategory: 'Relationships', category: 'Relationships and Family')
Interest.create(name: 'Relationships', subcategory: 'Relationships', category: 'Relationships and Family')
Interest.create(name: 'Weddings', subcategory: 'Relationships', category: 'Relationships and Family')
Interest.create(name: 'Women\'s Issues', subcategory: 'Relationships', category: 'Relationships and Family')
Interest.create(name: 'Atheist/Agnostic', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Buddhism', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Catholic', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Christianity', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Hinduism', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Islam', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Judaism', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Mormon', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Orthodox', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Paganism', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Protestant', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Religion', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Scientology', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Sufism', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Sunni', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Wicca', subcategory: 'Religion', category: 'Religion and Spirituality')
Interest.create(name: 'Astrology/Psychics', subcategory: 'Spirituality', category: 'Religion and Spirituality')
Interest.create(name: 'Mythology', subcategory: 'Spirituality', category: 'Religion and Spirituality')
Interest.create(name: 'New Age', subcategory: 'Spirituality', category: 'Religion and Spirituality')
Interest.create(name: 'Spirituality', subcategory: 'Spirituality', category: 'Religion and Spirituality')
Interest.create(name: 'Ecology', subcategory: 'Earth Sciences', category: 'Science and Mathematics')
Interest.create(name: 'Geoscience', subcategory: 'Earth Sciences', category: 'Science and Mathematics')
Interest.create(name: 'Marine Biology', subcategory: 'Earth Sciences', category: 'Science and Mathematics')
Interest.create(name: 'Meteorology', subcategory: 'Earth Sciences', category: 'Science and Mathematics')
Interest.create(name: 'Paleontology', subcategory: 'Earth Sciences', category: 'Science and Mathematics')
Interest.create(name: 'Zoology', subcategory: 'Earth Sciences', category: 'Science and Mathematics')
Interest.create(name: 'Alternative Energy', subcategory: 'Energy', category: 'Science and Mathematics')
Interest.create(name: 'Energy Industry', subcategory: 'Energy', category: 'Science and Mathematics')
Interest.create(name: 'Mining/Metallurgy', subcategory: 'Energy', category: 'Science and Mathematics')
Interest.create(name: 'Nuclear Science', subcategory: 'Energy', category: 'Science and Mathematics')
Interest.create(name: 'Petroleum', subcategory: 'Energy', category: 'Science and Mathematics')
Interest.create(name: 'Chemical Eng.', subcategory: 'Engineering', category: 'Science and Mathematics')
Interest.create(name: 'Civil Engineering', subcategory: 'Engineering', category: 'Science and Mathematics')
Interest.create(name: 'Electrical Eng.', subcategory: 'Engineering', category: 'Science and Mathematics')
Interest.create(name: 'Machinery', subcategory: 'Engineering', category: 'Science and Mathematics')
Interest.create(name: 'Manufacturing', subcategory: 'Engineering', category: 'Science and Mathematics')
Interest.create(name: 'Mechanical Eng.', subcategory: 'Engineering', category: 'Science and Mathematics')
Interest.create(name: 'Chaos/Complexity', subcategory: 'Mathematics', category: 'Science and Mathematics')
Interest.create(name: 'Logic', subcategory: 'Mathematics', category: 'Science and Mathematics')
Interest.create(name: 'Mathematics', subcategory: 'Mathematics', category: 'Science and Mathematics')
Interest.create(name: 'Statistics', subcategory: 'Mathematics', category: 'Science and Mathematics')
Interest.create(name: 'Biology', subcategory: 'Science', category: 'Science and Mathematics')
Interest.create(name: 'Chemistry', subcategory: 'Science', category: 'Science and Mathematics')
Interest.create(name: 'Physics', subcategory: 'Science', category: 'Science and Mathematics')
Interest.create(name: 'Science', subcategory: 'Science', category: 'Science and Mathematics')
Interest.create(name: 'Astronomy', subcategory: 'Space', category: 'Science and Mathematics')
Interest.create(name: 'Space Exploration', subcategory: 'Space', category: 'Science and Mathematics')
Interest.create(name: 'UFOs', subcategory: 'Space', category: 'Science and Mathematics')
Interest.create(name: 'Aviation/Aerospace', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Car Parts', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Cars', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Motor Sports', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Motorcycles', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Trains/Railroads', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Transportation', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Vintage Cars', subcategory: 'Cars and Transportation', category: 'Sports and Games')
Interest.create(name: 'Extreme Sports', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Skateboarding', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Skiing', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Skydiving', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Snowboarding', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Surfing', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Water Sports', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Windsurfing', subcategory: 'Extreme Sports', category: 'Sports and Games')
Interest.create(name: 'Billiards', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Board Games', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Card Games', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Chess', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Gambling', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Magic/Illusions', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Online Games', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Poker', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Puzzles', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Quizzes', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Roleplaying Games', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Toys', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Video Games', subcategory: 'Games', category: 'Sports and Games')
Interest.create(name: 'Boating', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Bowling', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Canoeing/Kayaking', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Fishing', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Flyfishing', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Golf', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Guns', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Hunting', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Sailing', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'Scuba Diving', subcategory: 'Leisure Sports', category: 'Sports and Games')
Interest.create(name: 'American Football', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Badminton', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Baseball', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Basketball', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Bicycling', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Bodybuilding', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Boxing', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Cheerleading', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Cricket', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Equestrian/Horses', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Figure Skating', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Fitness', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Gymnastics', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Hockey', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Martial Arts', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Racquetball', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Rodeo', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Rugby', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Running', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Soccer', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Sports(General)', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Squash', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Swimming', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Tennis', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Track/Field', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Volleyball', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Wrestling', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Yoga', subcategory: 'Sports', category: 'Sports and Games')
Interest.create(name: 'Animation', subcategory: 'Animation', category: 'TV & Movies')
Interest.create(name: 'Anime', subcategory: 'Animation', category: 'TV & Movies')
Interest.create(name: 'Cartoons', subcategory: 'Animation', category: 'TV & Movies')
Interest.create(name: 'Comic Books', subcategory: 'Animation', category: 'TV & Movies')
Interest.create(name: 'Multimedia', subcategory: 'Animation', category: 'TV & Movies')
Interest.create(name: 'Acting', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Action Movies', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Babes', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Celebrities', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Classic Films', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Comedy Movies', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Cult Films', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Drama Movies', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Film Noir', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Filmmaking', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Foreign Films', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Horror Movies', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Independent Film', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Movies', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Science Fiction', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Soap Operas', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Soundtracks', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'Television', subcategory: 'Television and Movies', category: 'TV & Movies')
Interest.create(name: 'A.I.', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Futurism', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Nanotech', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Robotics', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Semiconductors', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Supercomputing', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Virtual Reality', subcategory: 'AI and Robotics', category: 'Technology')
Interest.create(name: 'Computer Science', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Databases', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Embedded Systems', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Encryption', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Hacking', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Java', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Open Source', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'PHP', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Perl', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Programming', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Ruby on Rails', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Shareware', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Software', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Web Development', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Windows Dev', subcategory: 'Development', category: 'Technology')
Interest.create(name: 'Amateur Radio', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Audio Equipment', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Cell Phones', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Electronic Devices', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Electronic Parts', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Gadgets', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Ipod', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Mobile Computing', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Peripheral Devices', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Photo Gear', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Recording Gear', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Technology', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Telecom', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Video Equipment', subcategory: 'Gadgets', category: 'Technology')
Interest.create(name: 'Computer Hardware', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Computer Security', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Computers', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'IT', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Linux/Unix', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'MacOS', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Network Security', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Operating Systems', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Proxy', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Windows', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Internet', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Facebook', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Firefox', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Forums', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Instant Messaging', subcategory: 'Information Technology', category: 'Technology')
Interest.create(name: 'Internet Tools', subcategory: 'Internet', category: 'Technology')
Interest.create(name: 'P2P', subcategory: 'Internet', category: 'Technology')
Interest.create(name: 'Personal Sites', subcategory: 'Internet', category: 'Technology')
Interest.create(name: 'SEO', subcategory: 'Internet', category: 'Technology')
Interest.create(name: 'Search', subcategory: 'Internet', category: 'Technology')
Interest.create(name: 'Webhosting', subcategory: 'Internet', category: 'Technology')
Interest.create(name: 'Weblogs', subcategory: 'Internet', category: 'Technology')